### ISSUE TITLE
Upstream into CHIP?

### ISSUE THREAD

**Issue by woody-apple** [ARMmbed/connectedhomeip#10]
#### Problem
Is there a plan to move this upstream into CHIP?

 #### Proposed Solution
Please propose an upstream merge :)

**Comment by pan-** [comment]
Hi @woody-apple , thanks for the interest of this port. 
We're just starting but out goal is to contribute upstream with a solid Mbed OS port that would work on all the targets that mbed support. We will start pushing upstream once we have a fully working `Shell` example. 

Out of curiosity, What's the best way to engage with the upstream development team ? Is everything done through Github ? The ZA Slack seem a bit dead.
