### ISSUE TITLE
Check Thread variant lock application

### ISSUE THREAD

**Issue by pan-** [ARMmbed/connectedhomeip#115]
Instructions to reproduce it and expected results in the Wiki.

**Comment by lukgni** [comment]
Wiki page with description how to use Thread variant of lock-example can be found here:      
https://github.com/ARMmbed/connectedhomeip/wiki/Testing-Thread-variant--of-lock-application-(nrf-platform)

It mainly based on this guide:      
https://github.com/ARMmbed/connectedhomeip/blob/development/docs/guides/nrfconnect_android_commissioning.md 

Here is some changes which have been done according to:

- reusing prebuilded apk files from our android github workflow
- referencing prebuilded  OpenThread RCP firmware for second nrf52840 board
- modify section where nrf-prog is used to program nrf52840 board with 'pyocd flash reference'
- modify section with setting  Wi-Fi hotspot to use only terminal commands 
- adding expected log output when CHIP command is received by lock-app

Whole setup has been tested on the RPi4 with Ubuntu Server 20.10 and it worked as expected.
