### ISSUE TITLE
Build CHIP unit test application for Mbed

### ISSUE THREAD

**Issue by pan-** [ARMmbed/connectedhomeip#121]
To validate our integration, we must run the CHIP unit test application.

Outcome:
- CHIP unit test application available to Mbed 
- Build of the application in CI
- Tasks in VSCode to flash it 
- List of problematic tests that requires fix.

**Comment by fkjagodzinski** [comment]
The work is still in progress. Current state is available in https://github.com/ARMmbed/connectedhomeip/commits/test-unittests branch.
