### ISSUE TITLE
Linking errors when enabling 'Minimal mDNS' tests

### ISSUE THREAD

**Issue by lukgni** [ARMmbed/connectedhomeip#142]
#### Problem
After we pulled changes from upstream repository, we can't link with some of MinimalMdns function.

 #### Proposed Solution
1. List all MinimalMdns functions which causes that problem.
2. Check upstream repository for possible fix
3. Fix it!

**Comment by tymoteuszblochmobica** [comment]
GN scripts fixed and changes commited to test-unittests branch. All Minimal DNS tests are passed.
