### ISSUE TITLE
Enable Minimal mDNS unit tests

### ISSUE THREAD

**Issue by lukgni** [ARMmbed/connectedhomeip#143]
#### Problem
Enable Minimal mDNS unit-tests [gn deps]:
- /src/lib/mdns/minimal/tests
- /src/lib/mdns/minimal/core/tests
- /src/lib/mdns/minimal/responders/tests

 #### Proposed Solution
Enable Minimal mDNS unit-tests for mbed test application [CMakeList.txt, BUILD.gn]

#### Blocked by 
- #142

**Comment by tymoteuszblochmobica** [comment]
Minimal DNS unittests fixed and passed sucessfully.
Changes commited to test-unittests branch
