### ISSUE TITLE
Enable 'Messaging Layer' unit tests

### ISSUE THREAD

**Issue by lukgni** [ARMmbed/connectedhomeip#147]
#### Problem
Enable  'Messaging Layer' unit-tests [gn deps]:
- `/src/messaging/tests`

Linker module: 
- `libMessagingLayerTests`
 #### Proposed Solution
Enable 'Messaging Layer' unit-tests for mbed test application [CMakeList.txt, BUILD.gn]

 #### Blocked by
 - #141

**Comment by tymoteuszblochmobica** [comment]
Messaging layer tests fixed and now passing ok.
Changes commited to test-unittests
