### ISSUE TITLE
Define and provide an implementation of GroupKeyStore

### ISSUE THREAD

**Issue by pan-** [ARMmbed/connectedhomeip#23]
#### Problem
No implementation was required by our stubs so far but as we're integrating other parts of the configuration system, one is needed. 

 #### Proposed Solution
Implement the GroupKeyStore abstraction. It is implemented on other platforms: [example](https://github.com/ARMmbed/connectedhomeip/blob/demo/src/platform/qpg6100/GroupKeyStoreImpl.h)

**Comment by pan-** [comment]
The implementation is _trivial_ but not all the headers are present in the source tree. The base class is from Weave: `https://github.com/openweave/openweave-core/blob/5681a350aed5cc89eb8d358fb1db522ccde48af7/src/lib/profiles/security/WeaveApplicationKeys.h#L122` . 
I would be in favor of waiting a complete integration upstream so we can at least compile the file. 

That would move that issue out of Sprint 2. 

Any opinion @lukgni @ATmobica ?

**Comment by ATmobica** [comment]
What headers are not implemented?

**Comment by pan-** [comment]
The missing headers are from the base class: `::chip::Profiles::Security::AppKeys::GroupKeyStoreBase`. As linked above, they are present in the open weave repository.

**Comment by ATmobica** [comment]
Okay, now I understand. So we need to integrate Weave to mbed platform before -  next integration task. But I don't see the Wave source code inside the CHIP (even in third-party). Would it be available in platform-specific SDK?

**Comment by pan-** [comment]
Integration with Weave will be made upstream. I propose we wait for this integration to revisit this issue.

**Comment by ATmobica** [comment]
I think that's the right thing that we can do:)

**Comment by lukgni** [comment]
Yeah, I agree that we should wait for upstream integration.
