### ISSUE TITLE
Implement WiFi station primitives. 

### ISSUE THREAD

**Issue by pan-** [ARMmbed/connectedhomeip#33]
#### Problem
There is no Mbed implementation of GenericConnectivityManagerImpl_WiFi. just stubs. 

 #### Proposed Solution
Implement it. Stubs are declared [here](https://github.com/ARMmbed/connectedhomeip/blob/demo/src/include/platform/internal/GenericConnectivityManagerImpl_WiFi.h)

**Comment by tymoteuszblochmobica** [comment]
ConnectivityManagerImpl for WIFI implemented and merged
