### ISSUE TITLE
Create symbolic link in GIT

### ISSUE THREAD

**Issue by ATmobica** [ARMmbed/connectedhomeip#5]
#### Problem
Create a symbolic link in a project which is correctly interpreted by GIT.

 #### Solution
The reference path of the source file should be relative to the repository, not absolute to the machine.
More: [Symbolic links in Git](https://mokacoding.com/blog/symliks-in-git/)

**Comment by pan-** [comment]
This could probably part of the wiki. There is some problem with symbolic links on windows too. Maybe we should mention it there too.

**Comment by ATmobica** [comment]
That's right, I'll add this to the common wiki page about symlinks issues.
