### ISSUE TITLE
Set proper security type when connecting to WiFi

### ISSUE THREAD

**Issue by pan-** [ARMmbed/connectedhomeip#94]
#### Problem
On Mbed port, security type is _hardcoded_ to WPA WPA2 type when connecting to WiFi. This isn't correct for deployment. 

 #### Proposed Solution
Several options: 
- Allow Mbed API to skip setting the security type and let them do the work 
- Scan before connect at the chip level (very slow)
- Update provisioning so it include the Wifi security type.

**Comment by tymoteuszblochmobica** [comment]
Connectivity manager modified to allow override default security.
Already merged
